### ISSUE TITLE
add save option! 

### ISSUE THREAD

**Issue by gyke69** [JingWangTW/json-schema-editor#1]
add an option where we can choose our files which based on json (folder) and we be able to edit and save it. not export it everytime.

**Comment by JingWangTW** [comment]
Thanks for opening the very first issue for this project. This is a good suggestion. However, since the [File System Access API](https://caniuse.com/?search=file%20system%20access%20api) is not widely support at this point, this feature will be implemented after the API has been supported in most modern browsers. Before then, please export and import the same file while you are going to save the schema or start to edit the schema. Thanks
